[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Root -> /admin
[[redirects]]
  from = "/"
  to = "/admin"
  status = 301
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/booking/*"
  to = "/booking/:splat"
  status = 200
